# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-18 17:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('studeals', '0002_auto_20180315_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offer',
            name='description',
            field=models.CharField(default='No desciprion available', max_length=200),
        ),
        migrations.AlterField(
            model_name='offer',
            name='expiration_date',
            field=models.DateField(blank=True, default='2001/01/01'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='place_address',
            field=models.CharField(default='address unavailable', max_length=200),
        ),
        migrations.AlterField(
            model_name='offer',
            name='place_name',
            field=models.CharField(default='unavailable', max_length=30),
        ),
        migrations.AlterField(
            model_name='offer',
            name='price',
            field=models.CharField(default='n/a', max_length=20),
        ),
        migrations.AlterField(
            model_name='offer',
            name='title',
            field=models.CharField(default='Title', max_length=20),
        ),
    ]
