# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-18 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studeals', '0003_auto_20180318_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='title',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
