# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-18 20:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studeals', '0006_offer_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='date_added',
            field=models.DateField(default=datetime.date(2018, 3, 18)),
        ),
    ]
