# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-21 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studeals', '0012_auto_20180321_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(upload_to='media/profile_images'),
        ),
    ]
