# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-22 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studeals', '0014_auto_20180322_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='date_added',
        ),
        migrations.AlterField(
            model_name='offer',
            name='expiration_date',
            field=models.CharField(max_length=20),
        ),
    ]
